globalmart:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: chc70950.us-east-1
      user: SRINIVAS
      role: ACCOUNTADMIN
      database: GLOBALMART
      warehouse: COMPUTE_WH
      schema: PUBLIC
      threads: 4
      authenticator: programmatic_access_token
      token: "{{ env_var('SNOWFLAKE_TOKEN', '') }}"
