-- ============================================================
-- GlobalMart: Step 1 — Database, Schemas, File Formats
-- Uses existing COMPUTE_WH — no new warehouses created
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- Database
CREATE DATABASE IF NOT EXISTS GLOBALMART;

-- Schemas (5 total)
CREATE SCHEMA IF NOT EXISTS GLOBALMART.RAW;
CREATE SCHEMA IF NOT EXISTS GLOBALMART.BRONZE;
CREATE SCHEMA IF NOT EXISTS GLOBALMART.SILVER;
CREATE SCHEMA IF NOT EXISTS GLOBALMART.GOLD;
CREATE SCHEMA IF NOT EXISTS GLOBALMART.METRICS;

-- Use existing warehouse
USE WAREHOUSE COMPUTE_WH;

-- File formats
CREATE OR REPLACE FILE FORMAT GLOBALMART.RAW.CSV_FORMAT
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('', 'NULL', 'null')
  TRIM_SPACE = TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE OR REPLACE FILE FORMAT GLOBALMART.RAW.JSON_FORMAT
  TYPE = 'JSON'
  STRIP_OUTER_ARRAY = TRUE;
