-- ============================================================
-- GlobalMart: Step 6 — Streams + Tasks (auto-trigger dbt)
-- APPEND_ONLY streams detect new rows in RAW tables
-- Task checks all streams every 5 minutes
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE GLOBALMART;
USE SCHEMA RAW;
USE WAREHOUSE COMPUTE_WH;

-- Create APPEND_ONLY streams on each RAW table
CREATE OR REPLACE STREAM GLOBALMART.RAW.CUSTOMERS_STREAM
  ON TABLE GLOBALMART.RAW.RAW_CUSTOMERS_LOAD APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM GLOBALMART.RAW.ORDERS_STREAM
  ON TABLE GLOBALMART.RAW.RAW_ORDERS_LOAD APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM GLOBALMART.RAW.TRANSACTIONS_STREAM
  ON TABLE GLOBALMART.RAW.RAW_TRANSACTIONS_LOAD APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM GLOBALMART.RAW.RETURNS_STREAM
  ON TABLE GLOBALMART.RAW.RAW_RETURNS_LOAD APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM GLOBALMART.RAW.PRODUCTS_STREAM
  ON TABLE GLOBALMART.RAW.RAW_PRODUCTS_LOAD APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM GLOBALMART.RAW.VENDORS_STREAM
  ON TABLE GLOBALMART.RAW.RAW_VENDORS_LOAD APPEND_ONLY = TRUE;

-- Stored procedure placeholder for dbt execution
CREATE OR REPLACE PROCEDURE GLOBALMART.RAW.RUN_DBT_PIPELINE()
  RETURNS VARCHAR
  LANGUAGE SQL
AS
$$
BEGIN
  -- Placeholder: In production, this calls dbt Cloud API or executes dbt CLI
  -- via external function / Snowpark container
  RETURN 'dbt pipeline triggered at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- Task that checks streams every 5 minutes and triggers dbt
CREATE OR REPLACE TASK GLOBALMART.RAW.TRANSFORM_ON_NEW_DATA
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = '5 MINUTE'
  WHEN
    SYSTEM$STREAM_HAS_DATA('GLOBALMART.RAW.CUSTOMERS_STREAM')
    OR SYSTEM$STREAM_HAS_DATA('GLOBALMART.RAW.ORDERS_STREAM')
    OR SYSTEM$STREAM_HAS_DATA('GLOBALMART.RAW.TRANSACTIONS_STREAM')
    OR SYSTEM$STREAM_HAS_DATA('GLOBALMART.RAW.RETURNS_STREAM')
    OR SYSTEM$STREAM_HAS_DATA('GLOBALMART.RAW.PRODUCTS_STREAM')
    OR SYSTEM$STREAM_HAS_DATA('GLOBALMART.RAW.VENDORS_STREAM')
AS
  CALL GLOBALMART.RAW.RUN_DBT_PIPELINE();

-- Resume task (tasks are created suspended by default)
ALTER TASK GLOBALMART.RAW.TRANSFORM_ON_NEW_DATA RESUME;

-- Verify
SHOW STREAMS IN SCHEMA GLOBALMART.RAW;
SHOW TASKS IN SCHEMA GLOBALMART.RAW;
